//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChengQByIOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlTable
    {
        public int id { get; set; }
        public int use_count { get; set; }
        public int total_count { get; set; }
        public string url_code { get; set; }
        public string remark { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
